Document: pi-greeter
Title: Debian pi-greeter Manual
Author: <insert document author here>
Abstract: This manual describes what pi-greeter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pi-greeter/pi-greeter.sgml.gz

Format: postscript
Files: /usr/share/doc/pi-greeter/pi-greeter.ps.gz

Format: text
Files: /usr/share/doc/pi-greeter/pi-greeter.text.gz

Format: HTML
Index: /usr/share/doc/pi-greeter/html/index.html
Files: /usr/share/doc/pi-greeter/html/*.html
